Repository googleapis/python-video-transcoder, pull requests merged in 2021-04, with the labels that each got.

#39 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: transcoder, cla: yes, context: full

#40 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: transcoder, cla: yes, context: full, samples

#41 chore: prevent normalization of semver versioning
  setup.py
Labels: api: transcoder, cla: yes

#42 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: transcoder, automerge, cla: yes, context: full

#43 chore(revert): revert preventing normalization
  setup.py
Labels: api: transcoder, cla: yes
