Repository googleapis/python-video-transcoder, pull requests merged in 2022-01, with the labels that each got.

#125 chore: move samples from GoogleCloudPlatform/python-docs-samples
  README.rst
  samples/snippets/README.md
  samples/snippets/create_job_from_ad_hoc.py
  samples/snippets/create_job_from_preset.py
  samples/snippets/create_job_from_template.py
  samples/snippets/create_job_template.py
  samples/snippets/create_job_with_animated_overlay.py
  samples/snippets/create_job_with_concatenated_inputs.py
  samples/snippets/create_job_with_periodic_images_spritesheet.py
  samples/snippets/create_job_with_set_number_images_spritesheet.py
  samples/snippets/create_job_with_static_overlay.py
  samples/snippets/delete_job.py
  samples/snippets/delete_job_template.py
  samples/snippets/get_job.py
  samples/snippets/get_job_state.py
  samples/snippets/get_job_template.py
  samples/snippets/job_template_test.py
  samples/snippets/job_test.py
  samples/snippets/list_job_templates.py
  samples/snippets/list_jobs.py
  samples/snippets/noxfile.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
Labels: samples, lang: python, api: transcoder

#128 chore: set cdpe-cloudai as codeowner
  .github/CODEOWNERS
  .repo-metadata.json
  samples/snippets/noxfile.py
Labels: automerge, api: transcoder

#130 chore(cleanup): broken link in README
  README.rst
Labels: api: transcoder
